### ISSUE TITLE
想请教下打包思路是怎么样的 :)

### ISSUE THREAD

**Issue by 1369521908** [0312birdzhang/harbour-kuaidi#3]
如题

**Comment by 0312birdzhang** [comment]
这是 sailfishos的软件，需要用 Sailfish SDK打包，打开 harbour-kuaidi.pro 然后点左下角运行即可。

**Comment by 1369521908** [comment]
我的思路是纯用python+kivy来写,不知道是否可行,我想直接刷sailfishos来使用,但是机子下单还没到,有点尴尬...,喔买的是N9,相机蓝牙网络那些API可以用的吗?

**Comment by 0312birdzhang** [comment]
emmm，N9还是算了吧，太老了，建议米不多的话买个“印度鱼”，闲鱼上搜搜应该有
相机蓝牙网络那些用dbus应该可以，不过我不太会用。
没研究国kivy框架，只做逻辑的话那可以跟pyotherside结合起来用，要是用来显示界面的话可能不好做。

**Comment by 1369521908** [comment]
刚才搜了下油管，那个人能跑Python，到时候机子到了我试一下

**Comment by 0312birdzhang** [comment]
N9移植的旗鱼系统已经很旧了，体验一下的话那还行吧

**Comment by 1369521908** [comment]
备用机还是挺不错的,多写指教 :)

**Comment by 0312birdzhang** [comment]
> 备用机还是挺不错的,多写指教 :)

不客气，欢迎加入论坛 https://sailfishos.club 或者 https://t.me/jollacn 来讨论
